-
  name: Deploy a web application
  hosts: db_and_web_server
  tasks:
     
    - name: Install dependencies
      apt: 
        name: "{{ item }}" 
        state: present
        update_cache: yes
      with_items:
        - python3
        - python3-pip
        - build-essential
        - mysql-server
        - libmysqlclient-dev
        - python3-mysqldb

    - include: tasks/deploy_db.yml

    - include: tasks/deploy_web.yml